### PR TITLE
CI: skip code scanning on forks

### PR DESCRIPTION
**Pull request by chipitsine**
:cl:
CI: skip code scanning on forks
/:cl:

:cl: Categories
CI
/:cl:

[Why]: small improvement

### CODE REVIEW

**Comment by Cyberboss** [comment]
I don't understand why this is necessary. Code Scanning uses the default `GITHUB_TOKEN` which should be present on any repository.

**Comment by chipitsine** [comment]
image


image


I guess it want me to enable some code scanning storage which is not enabled by default

**Comment by Cyberboss** [comment]
It could potentially be a problem related to running in a private fork, which would cause all sorts of problems as it's not really supported. What's the full error you're getting.

**Comment by chipitsine** [comment]
it is public fork

https://github.com/ilia-shipitsin/tgstation-server/actions/runs/5193367388/jobs/9363821773

**Comment by Cyberboss** [comment]
Ahh, I know. The GitHub token must be too restrictive. It needs write access to generate the CodeQL status . You can set it under `settings/actions` (Write used to be the default but they must have changed it).
image

**Comment by chipitsine** [comment]
well, that is cosmetic, indeed.

I can either enable token permission or ignore red status.
I think people do not use Code scanning in forks (but I may be wrong)

**Comment by Cyberboss** [comment]
I've created the above PR to address this as it requires a new repository variable.

**Comment by chipitsine** [comment]
abandoning in favour of https://github.com/tgstation/tgstation-server/pull/1530

**Pull request closed without merging**
