### PR TITLE
Ability to publish testmerge commits to remote

### PR DESCRIPTION
**Pull request by Cyberboss**
Just for reference so they can be browsed on github

### CODE REVIEW

**Comment by MrStonedOne** [comment]
There is nowhere near enough info on this in this pr.

Is it optional? does it push to master? (I'd assume not, but i can't understand git.net's function/method layout)

**Comment by Cyberboss** [comment]
It's going to be optional yes, the way it works it it pushes a branch to github then immediately deletes it so the commits exist online and can be linked to without 404ing

**Comment by MrStonedOne** [comment]
cool now get @lzimann to exempt the branch name from zbot

**Comment by Cyberboss** [comment]
`___TGS3TempBranch`

**Comment by Cyberboss** [comment]
This isn't working because I can't figure out how to delete a remote branch using LibGit2Sharp

**Pull request merged**
