### PR TITLE
Save configuration after modification

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Would this work? Getting the `get;` autoproperty-generated backing field for modification in a custom `set {}` *IS* possible, but really really shitty.

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
why did i think i was modifying a class...

**Comment by vuonojenmustaturska** [comment]
How do you handle config loading? Will this replace the config with default values after reading name?

**Comment by vuonojenmustaturska** [comment]
image

**Comment by Cyberboss** [comment]
Mentioned this in IRC but posting this here for reference. Since the config uses JSON.Net's auto serializer, these changes may affect how those are written out and I'll have to confirm they dont

**Comment by MrStonedOne** [comment]
It shouldn't. the auto serializer only serializes public members and all of those work properly with getters and setters.

Thats from my experience with the soap serializer at least.

**Comment by Cyberboss** [comment]
im_drunk_and_what_could_go_wrong.ogg

**Pull request merged**
