### PR TITLE
CI: skip Doxygen builds on forks

### PR DESCRIPTION
**Pull request by ilia-shipitsin**
[Base Branch]: # (Please set the base branch of your pull request appropriately. If you only made a patch, code improvement, non-server code change, or comment/documentation update please target the `master` branch. Otherwise, target the `dev` branch.)

[Release Notes]: # (Your PR should contain a detailed list of notable changes, titled appropriately. This includes any observable changes to the server or DMAPI. See examples below.)

:cl:
Skip Doxygen build on forks
/:cl:

:cl: Categories
CI/:cl:

[Why]:  small improvement

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
We do want to always build the doxygen documents as part of the CI step to check for errors. Could you change this to only prevent the `gh-pages push` step? (Line 189)

Also, instead of hard coding the owner name, let's instead create a new secret that will trigger the push if set? Currently it piggybacks off of `secrets.DEV_PUSH_TOKEN` which is used for releases.

Last thing to note, just FYI. Since this PR is from a fork, you won't see your changes in the PR's actions due to how we use `pull_request_target`. That's not really relevant in the case of this PR, though, so don't worry about it.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
One more thing, since this is a CI improvement. Could you target our stable branch `master` instead of `dev` please?

**Comment by ilia-shipitsin** [comment]
> 

sure

**Comment by ilia-shipitsin** [comment]
well, I'm not sure how to make rule based on `DEV_PUSH_TOKEN`
if we add that to `env` variables, it will lead us to failure on fork if no such secret defined.

(as that workflow already fails on forks, it does not look like a benefit)

**Comment by Cyberboss** [comment]
You can set the secret to an `env` var and then check it with an `if: ${{
env.SECRET_NAME }}` in the step

**Comment by ilia-shipitsin** [comment]
abandoning in favour of https://github.com/tgstation/tgstation-server/pull/1522

**Pull request closed without merging**
