### PR TITLE
JobException InnerException Logging

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
[Base Branch]: # (Please set the base branch of your pull request appropriately. If you only made a patch, code improvement, non-server code change, or comment/documentation update please target the `master` branch. Otherwise, target the `dev` branch.)

[Release Notes]: # (Your PR should contain a detailed list of notable changes, titled appropriately. This includes any observable changes to the server or DMAPI. See examples below.)

Made this PR because I realised that testmerge conflicts DO actually say which PRs are conflicting, but only in the inner exception. Was originally going to just cram the PR confliction information into the main Exception, but was told to do otherwise. I can change it back if needed. Adjusts test to include an inner exception message since I thought it might be good to have, please tell me if this isn't useful and I'll remove it.

Did not test this, because it's such a minor change and setting up a dev environment seems highly time-consuming (I *will* do it if needed just don't want to have to if I don't need to), so I'm hoping that the unit tests catch everything.

:cl:
Logs JobExceptions' InnerException's message, allowing for better diagnosing of issues.
/:cl:

[Why]: # (If this does not close or work on an existing GitHub issue, please add a short description [two lines down] of why you think these changes would benefit the server. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Whoops, forgot to add secrets, doing so now

**Comment by MarkSuckerberg** [comment]
Required secrets added, checks should work now

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Bump the version to 4.16.3 in `build/Versions.props` please

**Comment by Cyberboss** [comment]
Yeah, 4.17.1 now

**Comment by MarkSuckerberg** [comment]
Bumped, thanks for your patience...

**Comment by AffectedArc07** [comment]
Opening this on a branch on the repo itself to deal with secrets memes

**Pull request closed without merging**
