### PR TITLE
Removes relay restart

### PR DESCRIPTION
**Pull request by Cyberboss**
Because bond fuckery it actually nreaks it instead of fixing ti

### CODE REVIEW

**Comment by Shadowlight213** [comment]
WARNING.
 CYBERBOSS MADE THIS WHILE DRUNK.

**Comment by Cyberboss** [comment]
My concious is friend not my brain

**Comment by Cyberboss** [comment]
Also no one merges here but me so HA

**Comment by Jordie0608** [comment]
Remove the irc error message saying to use this command.

**Pull request merged**
