### PR TITLE
TGS5

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
TGS now requires the ASP .NET 6 runtime to be installed to execute. You can download the runtime for install [here]().
File downloads made by TGS now have an appropriate User-Agent set.
The server will no longer automatically restart when saving configuration changes. Note that changes _may_ not apply until a restart is made.
Instance attach files renamed from `TGS4_ALLOW_INSTANCE_ATTACH` to `TGS_ALLOW_INSTANCE_ATTACH`. You will need to rename this file if you have any detached instances from v4.X.X you wish to attach after updating.
The server service no longer requires .NET Framework 4.7.2 to run, and thus no longer automatically installs.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
This will not pass CI until .NET 6 is fully released.

**Comment by AffectedArc07** [comment]
Obligatory quote
`TGS4 is set to be the final major version. There will be no TGS5, not from me.`

**Comment by AffectedArc07** [comment]
Nitpick:
`The server service no longer requires .NET Framework 4.7.2 to run, but also no longer automatically installs.`
words better as
`The server service no longer requires .NET Framework 4.7.2 to run, and thus no longer automatically installs.`

**Comment by Cyberboss** [comment]
Need to generate migrations before merging

**Comment by Fikou** [comment]
> This will not pass CI until .NET 6 is fully released.

.NET 6 released i think :D

**Comment by silicons** [comment]
:wave:

**Comment by Cyberboss** [comment]
Zzzz, I'm trying to do to much here

**Pull request closed without merging**
