### PR TITLE
Fix revision command using local revision

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
The `revision` chat command now shows the compile job's origin commit SHA as opposed to the local one.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Failed CI 3 times with
```
  X TestServer [5m 58s]
  Error Message:
   Assert.Fail failed. Incorrect number of DD processes: 2
```

**Comment by Cyberboss** [comment]
Networked CI is a pain in the fucking ass

**Comment by Cyberboss** [comment]
@optimumtact @ninjanomnom @Mothblocks give us back admin on this repo

**Comment by optimumtact** [comment]
@Cyberboss should be done

**Comment by AffectedArc07** [comment]
https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging

@Cyberboss

**Comment by AffectedArc07** [comment]
I cant actually trigger a CI re-run

**Review by AffectedArc07 — APPROVED** [review]
image

**Pull request merged**
