### PR TITLE
BYOND updates trigger a recompile

### PR DESCRIPTION
**Pull request by Cyberboss**
Duh

### CODE REVIEW

**Comment by MrStonedOne** [comment]
So, protip, you can freely compile with the new version while waiting for the round to end, just as long as you wait for the compile to complete before setting the flag that states you are waiting for the round to end.

This way you can also avoid any player visible issues if the compile fails

**Comment by Cyberboss** [comment]
This will have to be delayed until I rewrite ServerInstance

**Comment by MrStonedOne** [comment]
Why? we're in the middle of a beta cycle on byond, so this is the exact time something like this should be made and improved and tested, because its the exact time it will actually be used =P

**Comment by Cyberboss** [comment]
Blame my shitty initial architecture

**Comment by Cyberboss** [comment]
In all honesty though, it's about the same amount of work to make a cruddy hack that just works as it is to restructure the BYOND component properly

**Comment by Cyberboss** [comment]
The fix as is wouldn't work either, it'd just recompile using the previously installed version

**Pull request closed without merging**
