### PR TITLE
Adds webpanel v1.0.1 to the project

### PR DESCRIPTION
**Pull request by alexkar598**
:cl: Web Control Panel
Web panel v1.0.1 is now included in the project. It is accessible from `/app` or by accessing `/` from a browser.
The web panel can edit users, update the server, restart the server and access logs. Instance management will be included in a future update.
/:cl:

[Why]: # (If this does not close or work on an existing GitHub issue, please add a short description [two lines down] of why you think these changes would benefit the server. If you can't justify it in words, it might not be worth adding.)

The webpanel is complete enough to be used for user management and administration(updates, restart and logs). The instance editing features are still WIP

~~The webpanel is included using git subtree to add a subrepo into the TGS repo(basically submodules but requires less braincells to use and somewhat less flexible)~~

Its included by git cloning the repo at build time

The build script was changed to run npm ci when either package-lock.json or package.json was changed to rerun the install when the version is bumped as there may be a change in the post install scripts or something else we care about.

~~The command to update the web panel is to be ran from the root directory:
``git subtree pull --prefix=src/Tgstation.Server.Host/ClientApp/ https://github.com/tgstation/tgstation-server-control-panel.git <tag> --squash`` where <tag> is the tag name of the webpanel version to include~~ No longer a sub tree

### CODE REVIEW

**Comment by Rohesie** [comment]
The changelog format needs a prefix

**Comment by Cyberboss** [comment]
No it doesn't

**Comment by alexkar598** [comment]
Yeah I dont know how to fix this one mate

```
2020-10-12T23:39:13.1677124Z  [10/12/2020 11:38:47 PM +00:00] TEST ERROR: Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. LibGit2Sharp.NameConflictException: failed to stat 'C:/USERS/RUNNERADMIN/APPDATA/LOCAL/TEMP/TGS4_INTEGRATION_TEST/277EF052-F535-48D8-99EE-50AD5EDFD199/571F7566-1884-4CCF-853E-279C3D025CAB/Repository/src/Tgstation.Server.Host/ClientApp/scripts/patcher/files/@anttiviljami/dtsgenerator/dist/core/dtsGenerator.js.map': The filename or extension is too long.
```

**Comment by Cyberboss** [comment]
My changes remove the subtree, it's now brought in on demand at build time if necessary. You can set the version used in `build/ControlPanelVersion.props`.

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
