### PR TITLE
Update ControlPanelVersion to v2.2.0

### PR DESCRIPTION
**Pull request by alexkar598**
Updates webpanel to v2.2.0

:cl: Web Control Panel
Adds a page to select and install new byond versions.
Adds pagination to all lists, instead of only displaying 100 entries.
Adds a faint border to home screen icons.
Adds an automatic retry for user and server info.
Splits the functionality of the X button on jobs into two buttons, the X button dismisses completed jobs and a new button to the right of the progress bar lets you cancel the job.
Reworks all instance editing pages into a single page with tabs.
Removes the concept of "selecting instances". Jobs are now displayed for all instances.
Fixes a bug where the jobs widget would sometimes exit the viewport.
Fixes memory leaks.
Fixes bug where webpanel would not connect to TGS.
/:cl:

its coding socks time

### CODE REVIEW

**Comment by ZeWaka** [comment]
this is also a good time to mention `ControlPanel:Channel` doesn't default to anything and completely breaks the web panel from first install, until you ask alex what's wrong and have to search in the TGS releases for the value that should be there by default

**Comment by Cyberboss** [comment]
@ZeWaka it's not set in either `appsettings(.Production).yml`?

**Review by Cyberboss — APPROVED** [review]

**Comment by ZeWaka** [comment]
> @ZeWaka it's not set in either `appsettings[.Production].yml`?
@Cyberboss 
not by default setup, it's not even a blank entry

**Comment by legoscape** [comment]
fancy

**Pull request merged**
