### PR TITLE
Fixes README badges

### PR DESCRIPTION
**Pull request by san7890**
Same thing that broke for the tgstation project's readme (https://github.com/tgstation/tgstation/pull/77718 / https://github.com/tgstation/tgstation/commit/3957b77e9d725afc15022784a61daaa3a5d94091) was broken here, let's fix that in much the same way.

This PR is done because the original webhost server is down per https://github.com/BraveUX/for-the-badge/issues/252 .

### CODE REVIEW

**Comment by Cyberboss** [comment]
Feel free to create branches on the repo next time to avoid the PITA security checks

**Comment by Cyberboss** [comment]
Hnnnnnnggggh, binary filesssss

**Comment by Cyberboss** [comment]
@san7890, I'm going to upload these to https://file.house, can you update the links once I do and force-push out the .pngs?

**Comment by Cyberboss** [comment]
And link the FTB issue in your commit please

**Comment by san7890** [comment]
yes just let me know when

**Comment by Cyberboss** [comment]
Closing in favor of above PR

**Pull request closed without merging**
